apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitopsi-e2e-test-network-policy
  namespace: gitopsi-e2e-test-dev
  labels:
    app.kubernetes.io/name: gitopsi-e2e-test
    app.kubernetes.io/env: dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/env: dev
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/env: dev
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/env: dev

