apiVersion: v1
kind: ResourceQuota
metadata:
  name: gitopsi-e2e-test-quota
  namespace: gitopsi-e2e-test-dev
  labels:
    app.kubernetes.io/name: gitopsi-e2e-test
    app.kubernetes.io/env: dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "20"

