apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitopsi-e2e-test-apps-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://github.com/ihsanmokhlisse/gitopsitest
    targetRevision: HEAD
    path: applications/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: gitopsi-e2e-test-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

